<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Deterministic>true</Deterministic>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
