<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ini-parser-netstandard" />
    <PackageReference Include="MoonSharp" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Expressions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QueryCiv3\QueryCiv3.csproj" />
  </ItemGroup>
</Project>
