<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" />
    <PackageReference Include="Serilog" />
    <ProjectReference Include="..\Blast\Blast.csproj" />
  </ItemGroup>

</Project>
