name: "Cross-Platform Setup"
description: "Performs cross-platform build setup"

runs:
  using: "composite"
  steps:
  - name: Optionally set BUILD_SUFFIX
    shell: bash
    run: |
      if [[ ${{ github.event.inputs.debug-build || 'true' }} == 'true' ]]; then
        echo "BUILD_SUFFIX=-debug" >> $GITHUB_ENV
      else
        echo "BUILD_SUFFIX=-release" >> $GITHUB_ENV
      fi
  - name: Optionally set GH_USERNAME
    shell: bash
    if: github.event.inputs.include-username == 'true'
    run: |
      echo "GH_USERNAME=-${{ github.actor }}" >> $GITHUB_ENV
  - name: Optionally set BUILD_TIME
    shell: bash
    if: github.event.inputs.include-datetime == 'true'
    run: |
      echo "BUILD_TIME=-$(date --iso-8601=minutes | sed -e 's/:/-/g' | sed -e 's/\+.*//')" >> $GITHUB_ENV
  - name: Setup .NET 8
    uses: actions/setup-dotnet@v6
    with:
      dotnet-version: 8.0.423
  - name: Set FOLDER_NAME
    shell: bash
    run: |
      echo "FOLDER_NAME=${EXPORT_NAME}${{ github.event.inputs.folder-suffix || 'automated_build' }}${GH_USERNAME}${BUILD_TIME}" >> $GITHUB_ENV
  - name: Setup Godot export templates
    shell: bash
    run: |
      mkdir -v -p ~/.local/share/godot/export_templates
      mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
